apiVersion: v1
kind: Service
metadata:
  name: node-service
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: sample-node-service
