apiVersion: v1
kind: Service
metadata:
  name: node-service
  annotations:
    # references backendConfig so the correct health check path can be set upon backend creation in Google Cloud
    # Reference -> https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#associating_backendconfig_with_your_ingress
    cloud.google.com/backend-config: '{"default": "loadbalancer-backend-config"}'
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- if eq .Release.Namespace "default" }}
    app: sample-node-service
    {{ else }}
    app: "sample-node-service-{{ .Release.Namespace }}"
    {{- end }}
