apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: node-service-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-service
            port:
              number: 80
