name: push-to-public-ecr
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Check out repo inside of the container
            - uses: actions/checkout@v3

            # Build the container using the local Dockerfile and appedn the commit-sha to the image tag name
            # Ubuntu latest contains all of the dependencies I need to build the container (see https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md)
            - name: Build, tag, and push
              env: 
                ECR_REGISTRY: public.ecr.aws/mock-node-api
                ECR_REPOSITORY: lowsandbox
                IMAGE_TAG: sample-node-api-${{ github.sha }}
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG




